baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "Booster Timeline"
theme = "BT-theme"
enableGitInfo = true 
enableEmoji = true 
pygmentsUseClasses = true 

[markup.goldmark.renderer]
  unsafe = true
  
[params]

[outputs]
  home = ["HTML", "RSS"]

[taxonomies]

[markup]

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true
